# Configurazione per usare immagini da aggiungere agli eventi
media:
  input: "assets/events"    # cartella dove carichi le immagini dal CMS
  output: "/assets/events"  # percorso pubblico sul sito

# Configurazione dei contenuti
content:
  - name: "events"
    label: "Concerti"
    path: "events"   # cartella dove salvare i file JSON degli eventi
    type: "file"
    fields:
      - name: "title"
        label: "Titolo"
        type: string
        required: true

      - name: "description"
        label: "Descrizione"
        type: text
        required: true

      - name: "date"
        label: "Data"
        type: date
        required: true

      - name: "time"
        label: "Orario"
        type: string

      - name: "place"
        label: "Luogo"
        type: string
        required: true

      - name: "maps"
        label: "Google Maps Link"
        type: string

      - name: "tickets"
        label: "Ticket / Info Link"
        type: string

      - name: "video"
        label: "Video Link"
        type: string

      - name: "image"
        label: "Immagine"
        type: image
        required: true