content:
  - name: "events"
    label: "Concerti"
    folder: "events"
    media: 
      - name: "image"
        label: "Immagine Evento"
        type: "image"
        required: true
    fields:
      - name: "title"
        label: "Titolo"
        type: "string"
        required: true

      - name: "description"
        label: "Descrizione"
        type: "text"
        required: true

      - name: "date"
        label: "Data"
        type: "date"
        required: true

      - name: "time"
        label: "Orario"
        type: "string"

      - name: "place"
        label: "Luogo"
        type: "string"
        required: true

      - name: "maps_link"
        label: "Google Maps Link"
        type: "string"

      - name: "ticket_link"
        label: "Ticket / Info Link"
        type: "string"

      - name: "video_link"
        label: "Video Link"
        type: "string"

      - name: "status"
        label: "Stato Evento"
        type: "select"
        options:
          - "upcoming"
          - "past"
        required: true
        help: "Seleziona se l'evento è futuro (upcoming) o passato (past)"